Feature: Enable Scrolling and Strict Width to table
awcodes/filament-table-repeater pull request #94
Opened 2024-01-29 08:44 UTC by malzariey

I have faced a condition where I had many columns, static and dynamic ones. As shown below:
![Screenshot from 2024-01-29 11-38-58](https://github.com/awcodes/filament-table-repeater/assets/35528749/d4f0834d-48f8-4adf-a882-e667bfb994aa)

Added the features to enable scrolling and strictWidth to replace (th,td) width with min-wdith to enforce the columnWidths as shown below:
![Screenshot from 2024-01-29 11-22-29](https://github.com/awcodes/filament-table-repeater/assets/35528749/3f3a1b1c-45e7-4ea8-b9d8-055b1ef702ab)

2024-01-29 13:45 UTC, awcodes requested changes
Need to make sure this doesn't prevent the columns from stacking on mobile. The mobile stacking is one of the main features to the plugin.

Also please update the readme to reflect how to use these.

2024-01-29 13:45 UTC, awcodes commented on src/Components/TableRepeater.php
> +    public function getScrollable(): string
Can you change this to `shouldBeScrollable()` and update the view too.

2024-01-30 07:28 UTC, malzariey commented
> sure this doesn't prevent the columns from stacking on mobile. The mobile stacking is one of the main features to the plugin.

@awcodes  I have tried to test the breaking points, it doesn't seem to work for me (tried both modals and pages, any suggestions?), but I believe the the user will only use one of the two features, either scrollable or breakPoints.

Appreciate your comment

2024-02-06 08:24 UTC, malzariey commented
Canceled

2024-02-06 08:24 UTC, closed without merging